from app import app
from models import db, Update

with app.app_context():
    dummy_data = [
        Update(
            name="유세훈",
            employee_id="30046341",
            position="과장",
            week="Y25W27",
            project_summary="Ea placeat minus esse earum error.",
            milestones="Quis aliquam necessitatibus fuga. Ipsum illo harum sequi cum tempore.",
            progress="Earum consequatur et magnam. Repellendus magnam dicta distinctio labore atque.",
            project_issues="Pariatur aliquid neque deleniti.",
            sales_support="Illum incidunt nobis praesentium fuga.",
            other_notes="Iste accusantium sequi ea aliquam.",
            business_trip="A labore optio.",
            external_work="Fugit sit nobis ab.",
            vacation="Enim aperiam quae unde.",
            weekend_work="Iusto eum harum est dolorum."
        ),
        Update(
            name="김민욱",
            employee_id="30040640",
            position="차장",
            week="Y25W26",
            project_summary="Autem laborum molestias similique.",
            milestones="Eius possimus in tenetur. Quam quidem inventore molestiae molestiae nesciunt.",
            progress="Ipsam voluptatum aliquid eos.",
            project_issues="Exercitationem magni asperiores vero deserunt.",
            sales_support="Itaque modi repellendus.",
            other_notes="Dolor magni nostrum quas nostrum.",
            business_trip="Eum nemo occaecati.",
            external_work="Asperiores sequi eos modi.",
            vacation="Asperiores et harum.",
            weekend_work="Repudiandae amet fugit."
        ),
        Update(
            name="유세훈",
            employee_id="30046341",
            position="과장",
            week="Y25W25",
            project_summary="Quos accusantium corporis.",
            milestones="Eveniet itaque fugit aperiam. Similique molestias iusto optio quos.",
            progress="Ducimus accusantium modi cupiditate.",
            project_issues="Vel minima quam. Necessitatibus esse quasi inventore modi.",
            sales_support="Quis ab rerum.",
            other_notes="In ad est numquam ratione.",
            business_trip="Cumque aliquam hic natus.",
            external_work="Illo quam nulla cum.",
            vacation="Illum ipsam corrupti.",
            weekend_work="Repellat quod facere."
        ),
        Update(
            name="김정년",
            employee_id="30036413",
            position="대리",
            week="Y25W28",
            project_summary="Officia nulla distinctio nesciunt consequuntur placeat.",
            milestones="Cumque libero autem sapiente in nisi quasi.",
            progress="Quod commodi aperiam aperiam. Debitis eos atque a.",
            project_issues="Non blanditiis dolores. Beatae natus inventore repudiandae.",
            sales_support="Corrupti mollitia exercitationem velit officiis.",
            other_notes="Non impedit deserunt odit molestiae vel dolorum.",
            business_trip="Dolorem a repellat eius a.",
            external_work="Quo earum at facilis.",
            vacation="Nisi officiis odio iste.",
            weekend_work="Et cupiditate esse nam."
        ),
        Update(
            name="유혜빈",
            employee_id="30059497",
            position="사원",
            week="Y25W26",
            project_summary="Voluptatibus consequuntur nam minima impedit corrupti placeat quidem.",
            milestones="Beatae quos cupiditate laborum architecto cumque veniam rerum.",
            progress="At rem occaecati autem. Eveniet vel alias placeat incidunt ab accusantium.",
            project_issues="Incidunt architecto fuga explicabo rerum.",
            sales_support="Animi sint ad eligendi earum quod a.",
            other_notes="Cumque ea repellendus porro iste deleniti.",
            business_trip="Praesentium ipsa quisquam.",
            external_work="Aliquid qui vel.",
            vacation="Eos nobis nobis labore.",
            weekend_work="Laborum culpa hic ipsam eum."
        ),
        Update(
            name="김정은",
            employee_id="30056725",
            position="대리",
            week="Y25W26",
            project_summary="Est ex quas culpa veniam repellat.",
            milestones="Alias recusandae quidem rerum at occaecati. Nisi aut minus fugiat minus amet.",
            progress="Consequatur fugit expedita repudiandae.",
            project_issues="Repudiandae aut assumenda quod. Velit hic cupiditate.",
            sales_support="Est quaerat quibusdam tempore harum vel.",
            other_notes="Omnis animi quo rerum nemo.",
            business_trip="Nulla adipisci cum sapiente.",
            external_work="Minima autem maxime.",
            vacation="Aliquid atque nam.",
            weekend_work="Iusto deserunt sequi quo."
        ),
        Update(
            name="김강년",
            employee_id="30049038",
            position="대리",
            week="Y25W27",
            project_summary="Magnam adipisci ad sapiente dolore.",
            milestones="Vitae harum aperiam rem praesentium distinctio enim.",
            progress="Officiis expedita magnam ducimus quam expedita.",
            project_issues="Sint similique enim voluptate labore consequatur.",
            sales_support="Doloribus atque in quos atque quibusdam.",
            other_notes="Architecto qui id consequatur.",
            business_trip="Qui placeat sint deleniti.",
            external_work="Libero delectus optio cumque.",
            vacation="Fugit porro magnam.",
            weekend_work="Possimus ea quod laboriosam."
        ),
        Update(
            name="황태경",
            employee_id="30053653",
            position="대리",
            week="Y25W25",
            project_summary="Ipsum aliquam laudantium nam.",
            milestones="Rem dolore modi deserunt autem animi. Minima ad sed ipsum eaque inventore.",
            progress="Explicabo vero iure deleniti debitis deleniti voluptatibus.",
            project_issues="Temporibus minima dolore iste. Similique iusto cum.",
            sales_support="Temporibus ad repellat quas iusto asperiores amet.",
            other_notes="Quia in reiciendis voluptates non.",
            business_trip="At vitae unde cum.",
            external_work="Sed vel nulla autem optio.",
            vacation="Id odit cupiditate nobis.",
            weekend_work="Corporis esse eius."
        ),
        Update(
            name="민준홍",
            employee_id="30057537",
            position="차장",
            week="Y25W29",
            project_summary="Eius ipsum sint illum repellat a.",
            milestones="Fuga ipsum vel suscipit voluptatibus incidunt eius. Vel beatae ab molestiae.",
            progress="Ea et inventore quis.",
            project_issues="Sunt autem aliquam eaque quae quia.",
            sales_support="Dolorum voluptatibus sit a quaerat debitis quam.",
            other_notes="Velit non fuga.",
            business_trip="Nostrum reprehenderit sunt.",
            external_work="Ea itaque mollitia.",
            vacation="Beatae dolorem iure.",
            weekend_work="Est autem cum mollitia."
        ),
        Update(
            name="오윤석",
            employee_id="35001480",
            position="대리",
            week="Y25W29",
            project_summary="Blanditiis eligendi consectetur.",
            milestones="Laudantium eum debitis vitae vero velit accusamus sint.",
            progress="Officia similique omnis reprehenderit vel sunt tempora atque.",
            project_issues="Eveniet minus labore temporibus.",
            sales_support="Id odio unde dolores excepturi unde.",
            other_notes="Doloremque nam deleniti odio eum qui.",
            business_trip="Atque sint aliquam.",
            external_work="In doloribus culpa iusto.",
            vacation="Quia accusantium iure odio.",
            weekend_work="Labore inventore deleniti ad."
        ),
        Update(
            name="민준홍",
            employee_id="30057537",
            position="차장",
            week="Y25W26",
            project_summary="Consequuntur labore repellat aut.",
            milestones="Incidunt quae distinctio ad nihil quisquam doloribus.",
            progress="Qui laborum earum nemo esse. At debitis fuga eligendi iure non rem.",
            project_issues="Ipsa consequuntur suscipit eligendi rerum.",
            sales_support="Cumque facere maxime dolorum explicabo pariatur quo.",
            other_notes="Ratione pariatur ipsum ullam.",
            business_trip="Et autem in.",
            external_work="Animi sunt perferendis odio.",
            vacation="Alias delectus illum.",
            weekend_work="Quo placeat quis nemo."
        ),
        Update(
            name="김강년",
            employee_id="30049038",
            position="대리",
            week="Y25W26",
            project_summary="Architecto blanditiis ad.",
            milestones="Corporis earum voluptate voluptatibus aspernatur reiciendis.",
            progress="Doloribus necessitatibus laudantium maiores. Fugit expedita nulla labore.",
            project_issues="Nesciunt sequi ducimus mollitia magni ullam.",
            sales_support="Fugit minima officiis consectetur impedit rem.",
            other_notes="Nostrum doloremque adipisci vero nihil id.",
            business_trip="Molestias illo odit.",
            external_work="Tempore ab veniam.",
            vacation="Rem aut id.",
            weekend_work="Doloribus quia doloremque."
        ),
        Update(
            name="황태경",
            employee_id="30053653",
            position="대리",
            week="Y25W28",
            project_summary="Expedita laudantium atque cumque aliquam.",
            milestones="Consequatur voluptatibus assumenda assumenda natus nisi molestiae.",
            progress="Qui explicabo sint reprehenderit culpa vero aperiam.",
            project_issues="Enim quo magni tenetur necessitatibus.",
            sales_support="Non neque numquam.",
            other_notes="Dolores deleniti aliquam nam totam rerum.",
            business_trip="Nostrum doloribus iste.",
            external_work="Libero optio ullam quas.",
            vacation="Omnis amet qui repellat odio.",
            weekend_work="Nostrum a dolorum est."
        ),
        Update(
            name="황태경",
            employee_id="30053653",
            position="대리",
            week="Y25W26",
            project_summary="Numquam distinctio laudantium doloremque.",
            milestones="Nulla dolor consequuntur.",
            progress="Maiores porro rem odio. Fugit cumque vero perspiciatis.",
            project_issues="Minus harum reiciendis magnam labore quaerat.",
            sales_support="Quasi fugit velit.",
            other_notes="Nihil deserunt alias ipsa nemo inventore.",
            business_trip="Sequi sint et eum.",
            external_work="Recusandae eum assumenda est.",
            vacation="Iure culpa porro ipsam.",
            weekend_work="Sunt corporis alias."
        ),
        Update(
            name="김정년",
            employee_id="30036413",
            position="대리",
            week="Y25W29",
            project_summary="Officiis facilis assumenda labore.",
            milestones="Vel deleniti illum vitae deleniti dolore.",
            progress="Quas ad cum fugiat in eligendi. Tempore cupiditate hic suscipit aliquid.",
            project_issues="Exercitationem eaque quos quidem. Deleniti culpa eius quo.",
            sales_support="Laudantium accusantium sint accusamus.",
            other_notes="Illum nisi distinctio odit.",
            business_trip="Pariatur vero mollitia ut.",
            external_work="Consequuntur ex in nostrum.",
            vacation="Quae tempora molestiae.",
            weekend_work="Dicta quidem ea enim."
        ),
        Update(
            name="김민욱",
            employee_id="30040640",
            position="차장",
            week="Y25W26",
            project_summary="Optio deleniti enim accusamus magnam incidunt.",
            milestones="Quam sed tempora. Facilis laudantium commodi sit. Ut odit tempora id.",
            progress="Sapiente nobis totam eos. Ab officiis doloremque incidunt dicta cumque minima.",
            project_issues="Labore distinctio fuga quos quos molestias.",
            sales_support="Est aut voluptatem molestiae explicabo.",
            other_notes="Veniam nemo labore tempora odio commodi.",
            business_trip="Aut eligendi provident animi.",
            external_work="Sit ex vitae a.",
            vacation="Dolorem dolor distinctio.",
            weekend_work="Quos quo maiores est."
        ),
        Update(
            name="박현민",
            employee_id="35003195",
            position="대리",
            week="Y25W27",
            project_summary="Voluptatem consequatur beatae facilis incidunt.",
            milestones="Asperiores rem quod vero. Eum provident accusamus minima dolor nisi ea.",
            progress="Cupiditate quasi unde numquam dignissimos.",
            project_issues="Nulla laudantium voluptatem ducimus similique molestias.",
            sales_support="Laborum quisquam accusantium iste reiciendis.",
            other_notes="Eaque commodi ea velit.",
            business_trip="Suscipit odit molestias.",
            external_work="Nam provident ratione quo.",
            vacation="Dolor sed nihil magni.",
            weekend_work="Atque et placeat corrupti."
        ),
        Update(
            name="민준홍",
            employee_id="30057537",
            position="차장",
            week="Y25W26",
            project_summary="Qui rerum eaque provident necessitatibus deserunt impedit ad.",
            milestones="Repellendus quasi blanditiis cum et necessitatibus dolorum magni.",
            progress="Nulla odio quis dolorum non. Explicabo iure impedit voluptatem nisi.",
            project_issues="Eveniet repellendus quod molestias recusandae error sint.",
            sales_support="Id quisquam fugit placeat sed autem.",
            other_notes="Quasi corrupti illum animi atque.",
            business_trip="Nisi officiis incidunt.",
            external_work="Quia saepe maxime.",
            vacation="Eos rem ut ea.",
            weekend_work="Itaque eaque voluptatum non."
        ),
        Update(
            name="오윤석",
            employee_id="35001480",
            position="대리",
            week="Y25W27",
            project_summary="Ipsum a neque est libero cum sit molestiae.",
            milestones="Dolore magnam ipsam voluptates laboriosam.",
            progress="Repudiandae minima ab voluptate ad.",
            project_issues="Eius dolorem quidem ea.",
            sales_support="Consequatur perferendis saepe nisi magni quaerat.",
            other_notes="Enim necessitatibus sit molestias ducimus eaque.",
            business_trip="Vero saepe dolore.",
            external_work="Dolor ducimus soluta.",
            vacation="Magni harum reprehenderit.",
            weekend_work="Iure illum id."
        ),
        Update(
            name="김민욱",
            employee_id="30040640",
            position="차장",
            week="Y25W29",
            project_summary="Quam ipsum illum consequuntur quam nemo.",
            milestones="Atque eaque deserunt. Placeat repudiandae ullam sed eum odio at.",
            progress="Voluptatem accusamus enim facilis saepe omnis.",
            project_issues="Possimus itaque totam facere odit.",
            sales_support="Dolorem eligendi eius nisi nam.",
            other_notes="Quasi vero laborum culpa magnam.",
            business_trip="Soluta maxime modi.",
            external_work="Assumenda totam nemo quod.",
            vacation="Facere quos adipisci dolorum.",
            weekend_work="Dolore quia tenetur."
        ),
    ]
    db.session.bulk_save_objects(dummy_data)
    db.session.commit()
    print('Dummy data inserted successfully.')