"""fix model binding

Revision ID: aa162b2ed047
Revises: 
Create Date: 2025-07-18 12:46:04.164024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa162b2ed047'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solution_name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_code'), ['code'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_employee_id'), ['employee_id'], unique=True)

    op.create_table('project_assignees',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.String(length=10), nullable=False),
    sa.Column('progress', sa.Text(), nullable=False),
    sa.Column('project_issues', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', 'week', name='uix_user_project_week')
    )
    with op.batch_alter_table('update', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_update_week'), ['week'], unique=False)

    op.create_table('other_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['update_id'], ['update.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('출장', '외근', '휴가', '휴일근무', name='schedule_category'), nullable=False),
    sa.Column('person', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['update_id'], ['update.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_support',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('system', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('companion', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['update_id'], ['update.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_support')
    op.drop_table('personal_schedule')
    op.drop_table('other_note')
    with op.batch_alter_table('update', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_update_week'))

    op.drop_table('update')
    op.drop_table('project_assignees')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_employee_id'))

    op.drop_table('user')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_code'))

    op.drop_table('project')
    # ### end Alembic commands ###
